# Generated by Django 5.1 on 2024-08-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cedula', models.CharField(max_length=100)),
                ('telofono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=100)),
                ('datacreate', models.DateField(auto_now=True)),
            ],
        ),
    ]
